import Head from 'next/head'
import PageLayout from '@/components/PageLayout'


export default function Home() {
  return (
    <>
      <Head>
        <title>Tawi&apos;s Bloom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <PageLayout />
      </main>  
    </>
  )
}
